name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build-and-publish-back:
    name: build and publish back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t deploy backend/.
          docker tag deploy:latest 156138231205.dkr.ecr.eu-central-1.amazonaws.com/backend:v1
          docker push 156138231205.dkr.ecr.eu-central-1.amazonaws.com/backend:v1
          echo "::set-output name=image::156138231205.dkr.ecr.eu-central-1.amazonaws.com/backend:v1"
          
   build-and-publish-front:
    name: build and publish front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t deploy front/.
          docker tag deploy:latest 156138231205.dkr.ecr.eu-central-1.amazonaws.com/front:v1
          docker push 156138231205.dkr.ecr.eu-central-1.amazonaws.com/front:v1
          echo "::set-output name=image::156138231205.dkr.ecr.eu-central-1.amazonaws.com/front:v1"


  
    

   
